# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Create env file
      run: |
        npm install
        npm test
      env:
        MONGO_URI : ${{ secrets.MONGO_URI }}
        COOKIE_SECRET : ${{ secrets.COOKIE_SECRET }}
        JWT_COOKIE_EXPIRE_DATE: ${{ secrets.JWT_COOKIE_EXPIRE_DATE }}
        JWT_EXPIRE_DATE: ${{ secrets.JWT_EXPIRE_DATE }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    - name: Run unit tests with coverage
      run: |
        SUMMARY="$(npm test --coverage --coverageReporters=text-summary | tail -3 | head -1)"
        TOKENS=($SUMMARY)
        echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV

    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 8effb3f12e575124c19dc2b50aa632f8
        filename: stot_coverage.json
        label: coverage
        message: ${{ env.COVERAGE }}
        namedLogo: jest
        color: blue
        logoColor: lightblue